### ISSUE TITLE
Outputting PMML 4.2 on spark 2.0.x

### ISSUE THREAD

**Issue by sdjksdafji** [jpmml/pyspark2pmml#1]
Hi Villu, 

I would like to thank you for contributing on these projects. I found the libraries are extremely useful.

I am wondering is there a setting to choose which PMML version to output ? I have a PMML evaluator which only works for PMML 4.2.  @vruusmann

**Comment by sdjksdafji** [comment]
Ping @vruusmann

**Comment by sdjksdafji** [comment]
Resolved.

**Comment by Handyou** [comment]
hello, I use PMMLBuilder get a pmml, but the head of pmml is <PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable"  version="4.3">, and I use this pmml to predict is all None,why ? Can i change pmml-4_4 to pmml-4_3?
