### ISSUE TITLE
AttributeError: 'PMMLBuilder' object has no attribute 'buildFile'

### ISSUE THREAD

**Issue by oaksharks** [jpmml/pyspark2pmml#12]
I followed the readme.md like:

```python
from pyspark2pmml import PMMLBuilder
pmmlBuilder = PMMLBuilder(sc, df, pipelineModel) \
	.putOption(classifier, "compact", True)
pmmlBuilder.buildFile("DecisionTreeIris.pmml")
```
but occur an error :
```
AttributeError: 'PMMLBuilder' object has no attribute 'buildFile'
```
I have used `buildByteArray()` instead .

**Comment by vruusmann** [comment]
The `PMMLBuilder.buildFile(path)` method is defined right here:
https://github.com/jpmml/pyspark2pmml/blob/master/pyspark2pmml/__init__.py#L26-L29

Perhaps you should upgrade your `pyspark2pmml` package version.
