### ISSUE TITLE
installation method on spark cluster

### ISSUE THREAD

**Issue by yairdata** [jpmml/pyspark2pmml#19]
hi , a question about installation method .
the jar of jpmml-sparkml can be broadcasted to all workers since we use the --jars flag, but does the pyspark2pmml wrapper need to be installed only on the edge node or on all the workers as well ?

**Comment by vruusmann** [comment]
I have no idea.

Moreover, I think that this question ("how do I distribute a Python wrapper for a Apache Spark package") really belongs to Apache Spark mailing list.
