### ISSUE TITLE
Unicode issue 

### ISSUE THREAD

**Issue by avisheknag17** [jpmml/pyspark2pmml#24]
I am running pyspark2pmml and getting below error
```
File "/opt/spark-2.2.1-master/bin/enclosures_pyspark_model.py", line 125, in _build_individual_model_
    pmml_bytes = pmml_builder.buildByteArray()
  File "/Users/avnag/Library/Python/2.7/lib/python/site-packages/pyspark2pmml/__init__.py", line 23, in buildByteArray
    return self.javaPmmlBuilder.buildByteArray()
  File "/opt/spark-2.2.1-master/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/spark-2.2.1-master/python/lib/pyspark.zip/pyspark/sql/utils.py", line 79, in deco
pyspark.sql.utils.IllegalArgumentException: u'even\u2014'
```
It is not occurring always and randomly coming one or two times. In fact I have set gloval encoding as 'UTF-8'
``` python
import sys
reload(sys)  # Reload is a hack
sys.setdefaultencoding('UTF-8')
```

My source code for generating PMML
``` python
pmml_builder = PMMLBuilder(sc, train_df, pl_model).verify(train_df.sample(False, 0.1))
pmml_bytes = pmml_builder.buildByteArray()
pmml_str = pmml_bytes.decode("UTF-8")

f = open('category_classifier_' + category_col.replace(' ', '_') + '.pmml', 'w')
f.write(pmml_str)
f.close()
```
Any idea why this error is coming randomly ?

**Comment by vruusmann** [comment]
> pyspark.sql.utils.IllegalArgumentException: u'even\u2014'

This is a PySpark layer exception, which is a layer beneath the PySpark2PMML package/layer.

I don't do generic Python support.

> Any idea why this error is coming randomly?

In some training runs, your model picks up a "feature" that requires Unicode character set for its representations. The Java layer sends out a correct UTF-8 byte array, but the PySpark layer is unable to accept it properly.

It's probably an Apache Spark configuration issue.
