### ISSUE TITLE
Excepted string,integral,double or boolean type, got array type

### ISSUE THREAD

**Issue by bfgf52** [jpmml/pyspark2pmml#26]
I want to use CountVectorizer in my project.
>>> df = spark.createDataFrame(
...    [(0, ["a", "b", "c"]), (1, ["a", "b", "b", "c", "a"])],
...    ["label", "raw"])
>>> cv = CountVectorizer(inputCol="raw", outputCol="vectors")
>>> model = cv.fit(df)
>>> lr = LogisticRegression(featuresCol='vectors', labelCol='label')
>>>pipeline = Pipeline(stages = [cv , lr ])
>>>pipelineModel = pipeline.fit(df)

>>>from pyspark2pmml import PMMLBuilder
>>>pmmlBuilder = PMMLBuilder(sc, df, pipelineModel) 
>>>pmmlBuilder.buildFile("LogisticRegression.pmml")

but I got Excepted string,integral,double or boolean type, got array type error.How can I solve it if column is arraytype?

**Comment by vruusmann** [comment]
"Array data type is not supported" is a variant of the "Vector data type is not supported" theme, see https://github.com/jpmml/jpmml-sparkml/issues/26 for more insight.

Possible workarounds:

1. Make the "beginning" of the pipeline longer. Right now your pipeline starts with array column(s), but there should be an extra step prepended which shows how these array column(s) were derived from scalar column(s). Can't you apply `CountVectorizer` directly to a scalar column?
2. Use vector assemblers and slicers to "explode" array column(s) into scalar columns.
3. Write a custom Apache Spark transformer plus JPMML-SparkML transformer converter to deal with array column(s) as-is.

**Comment by damonjun512** [comment]
Have same problem.i try to make a new dataframe. but it don't work.
` val dataframe1=vecDF.select("index","features").toDF("index","features")
    val schema:StructType = dataframe1.schema;
    val pmml= new PMMLBuilder(schema, model)`

**Comment by marvinxu-free** [comment]
> "Array data type is not supported" is a variant of the "Vector data type is not supported" theme, see [jpmml/jpmml-sparkml#26](https://github.com/jpmml/jpmml-sparkml/issues/26) for more insight.
> 
> Possible workarounds:
> 
> 1. Make the "beginning" of the pipeline longer. Right now your pipeline starts with array column(s), but there should be an extra step prepended which shows how these array column(s) were derived from scalar column(s). Can't you apply `CountVectorizer` directly to a scalar column?
> 2. Use vector assemblers and slicers to "explode" array column(s) into scalar columns.
> 3. Write a custom Apache Spark transformer plus JPMML-SparkML transformer converter to deal with array column(s) as-is.

colud you give some example for these 3 workarounds? cause i found write a user defined transformer is not easy
