### ISSUE TITLE
Exception while running pyspark2pmml

### ISSUE THREAD

**Issue by aliware50** [jpmml/pyspark2pmml#27]
My code looks like this :
```python
from pyspark2pmml import PMMLBuilder

pmmlBuilder = PMMLBuilder(sc, train_df, pl) \
    .putOption(classifier, "compact", True)
```

While running it is throwing exception
```
py4j.protocol.Py4JError: An error occurred while calling None.org.jpmml.sparkml.PMMLBuilder. Trace:
py4j.Py4JException: Constructor org.jpmml.sparkml.PMMLBuilder([class org.apache.spark.sql.types.StructType, class org.apache.spark.ml.classification.LogisticRegressionModel]) does not exist
```

**Comment by vruusmann** [comment]
> Constructor org.jpmml.sparkml.PMMLBuilder([class org.apache.spark.sql.types.StructType, class org.apache.spark.ml.classification.LogisticRegressionModel]) does not exist

The cause is clearly explained in the exception message - there is no `PMMLBuilder` constructor that would accept an `org.apache.spark.ml.classification.LogisticRegressionModel` object as a third parameter (must be an `org.apache.spark.ml.PipelineModel` object instead).
