### ISSUE TITLE
Cannot store the PMML byte array to an HDFS location

### ISSUE THREAD

**Issue by ncepumas** [jpmml/pyspark2pmml#30]
Code:
.buildFile("hdfs:/hz-cluster9/user/portal/hive/lr.pmml") 

ERROR:
py4j.protocol.Py4JJavaError: An error occurred while calling o573.buildFile.
: java.io.FileNotFoundException: hdfs:/hz-cluster9/user/portal/hive/lr.pmml (No such file or directory)

help!!!

**Comment by vruusmann** [comment]
The path argument must be a file path (file in a local filesystem). You're supplying an URL instead.

Save the PMML document into local computer, and then copy it over to the final destination (some HDFS location) using more appropriate tools.

**Comment by ncepumas** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your answer! I submitted the task to run on the cluster and set the address to a local file, for example, "lr. pmml". But the problem now is that the exported file is empty. For help again!
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhaoyh
                            
                    
                        
                            
                                    zhaoyh@ncepu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/22/2020 23:45，Villu Ruusmann<notifications@github.com> wrote： 



The path argument must be a file path (file in a local filesystem). You're supplying an URL instead.
Save the PMML document into local computer, and then copy it over to the final destination (some HDFS location) using more appropriate tools.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
