### ISSUE TITLE
Failed to save custom model as pipeline

### ISSUE THREAD

**Issue by gongjunjun** [jpmml/pyspark2pmml#31]
Can this package only save the models built in the spark ml library?

**Comment by vruusmann** [comment]
> Can this package only save the models built in the spark ml library?

As the package name suggests ("PySpark to PMML"), then this package is intended for converting Apache Spark ML pipelines (transformers and models) to the PMML representation.

For other ML frameworks there are other packages. For example, [Scikit-Learn-to-PMM](https://github.com/jpmml/sklearn2pmml)L, [R-to-PMML](https://github.com/jpmml/r2pmml).

Closing this question as "too vague". Generic topics should be discussed in the JPMML mailing list at https://groups.google.com/forum/#!forum/jpmml

**Comment by gongjunjun** [comment]
Pyspark :  I use package named ‘sparkflow’ to creat a model, It supports saving the training result as pipeline, when I try to save as pmml, it cannot be saved,so I want to know Can this package(pysparkpmml) only save the models built in the spark ml library?
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Villu Ruusmann<mailto:notifications@github.com>
发送时间: 2020年7月9日 17:03
收件人: jpmml/pyspark2pmml<mailto:pyspark2pmml@noreply.github.com>
抄送: gongjunjun<mailto:light.G@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jpmml/pyspark2pmml] Failed to save custom model as pipeline (#31)


Closed #31<https://github.com/jpmml/pyspark2pmml/issues/31>.

―
