### ISSUE TITLE
How do I save the files generated by the kmeans model

### ISSUE THREAD

**Issue by WangxuP** [jpmml/pyspark2pmml#41]
spark: 2.4.8
pyspark2pmml: 0.5.0
jars: jpmml-sparkml-executable-1.5.1.jar
error logs is below:
![image](https://github.com/jpmml/pyspark2pmml/assets/14866506/bb39cd79-fc59-431d-b55d-9d4f405b7bf2)

**Comment by vruusmann** [comment]
> jpmml-sparkml-executable-1.5.1.jar

That's a 4 YEARS OLD version (released on 20th of February, 2019).

You know what to do. I'm not going to waste my time on this.

**Comment by WangxuP** [comment]
That's too bad, because my Spark is version 2.4, and I'm planning to spend a lot of money to purchase your license, but you don't support it anymore. point out with great  regret;

**Comment by vruusmann** [comment]
> and I'm planning to spend a lot of money to purchase your license,

TBH, I don't believe you.

> my Spark is version 2.4, .. , but you don't support it anymore

Apache Spark 2.4 is supported.

You should simply update your JPMML-SparkML library from 1.5.1 (FOUR YEARS OLD) to 1.5.14. You are missing something like 12-13 library versions worth of updates.

After you update to 1.5.14, the error message should be much clearer. It's probably related to the naming of dataframe columns.

**Comment by vruusmann** [comment]
> You should simply update your JPMML-SparkML library from 1.5.1 (FOUR YEARS OLD) to 1.5.14. 

See here:
https://github.com/jpmml/jpmml-sparkml/releases

Look for the latest "1.5.X" release.

On the second page, there is a 1.5.14 uber-JAR file available:
https://github.com/jpmml/jpmml-sparkml/releases/tag/1.5.14

**Comment by WangxuP** [comment]
> > You should simply update your JPMML-SparkML library from 1.5.1 (FOUR YEARS OLD) to 1.5.14.
> 
> See here: https://github.com/jpmml/jpmml-sparkml/releases
> 
> Look for the latest "1.5.X" release.
> 
> On the second page, there is a 1.5.14 uber-JAR file available: https://github.com/jpmml/jpmml-sparkml/releases/tag/1.5.14

I'm very sorry, I'm using pyspark for model training instead of Java，But the solution you just provided seems to be using Java, and I am not a Java engineer.
when I use  JPMML-SparkML1.5.14. the error log is below:
![image](https://github.com/jpmml/pyspark2pmml/assets/14866506/940c084f-e62b-4e1e-beae-651f04747bfb)

**Comment by vruusmann** [comment]
> I'm using pyspark for model training instead of Java，But the solution you just provided seems to be using Java

Please elaborate.

Your only responsibility is to tell Apache Spark version 2.4 the following: "please download and activate JPMML-SparkML library version 1.5.14 for this session". You can do this using `--packages` or `--jars` command-line arguments.

There is no Java programming involved.

> when I use JPMML-SparkML1.5.14. the error log is below:

Looks like everything is working correctly for you.

The updated JPMML-SparkML library clearly states what is the problem with your pipeline: `IllegalArgumentException: Name cannot be empty`

It means that at least one of your features uses an empty string `""` as its name. This is not allowed, you must change it to some meaningful (ie. non-empty) name.

Use "x1", "x2" or whatever, not empty strings.
