### ISSUE TITLE
Pyspark  "Multinomial logistic regression" InterceptVector Problem

### ISSUE THREAD

**Issue by sbourzai** [jpmml/pyspark2pmml#7]
Hi Sir,
I Try to get my PMML file for a Multinomial logistic Regression with Iris data, but i think that the function toPMMLBytes take not in consideration the InterceptVector 
Ithink that the problem is at this level : 
----> 8         javaPipelineModel = pipelineModel._to_java()

I get this message : 
Py4JJavaError:
 An error occurred while calling z:org.jpmml.sparkml.ConverterUtil.toPMMLByteArray.
: org.apache.spark.SparkException: Multinomial models contain a vector of intercepts, use interceptVector instead.
	at org.apache.spark.ml.classification.LogisticRegressionModel.intercept(LogisticRegression.scala:731)

NB : I was able to get my pmml model with the Titanic data ( Binary logistic Regression ) 

Have any Idea ?

Thanks,
Kind Regards

**Comment by vruusmann** [comment]
Multinomial logistic regression was introduced in Apache Spark 2.1.X.

You must use JPMML-SparkML version that is compatible with your Spache Spark version, see the version compatibility matrix in the README file:
https://github.com/jpmml/jpmml-sparkml#library

**Comment by sbourzai** [comment]
Thanks @vruusmann , I'm using Pyspark, the build don't produce the egg file !!!
