### ISSUE TITLE
NaiveBayes models "Pyspark"

### ISSUE THREAD

**Issue by sbourzai** [jpmml/pyspark2pmml#8]
It seems that the NaiveBayes models are not exportable with your package jpmml sparkML
I got this message Exception : 
IllegalArgumentException_: **u'Transformer class org.apache.spark.ml.classification.NaiveBayesModel is not supported'**
Are you working on it for the next version ? 
Thank you in advance !!

Saad

**Comment by rajpalparyani** [comment]
We are also interested in this .. Is there any plans of working on it now ?
